### PR TITLE
feat: client deployment

### PR DESCRIPTION
**Pull request by woodyjon**
- remove infura id from .env file
- dxc port to be specified by user in .env file and combine host and port so that it works successfully on any kind of server in conjonction with the dxs

### CODE REVIEW

**Comment by goosecoid** [comment]
LGTM

Only one remark, what if the infura ID changes in the future? Then everybody needs to update their DXC. Can we not store the infura ID on the DXS and have a route to GET the ID and a PUT to update it if necessary? Now that I read this, it's maybe overkill, but I think it will save us a lot of future headaches.

**Comment by woodyjon** [comment]
I don't know. Seems to me that Vincent wants to limit all manual steps. So getting it from the DXS is an additional thing that he will not like, I think.

**Comment by goosecoid** [comment]
Yes, I understand. But if we would store the infura id on the DXS DB. We could fetch always the latest id via an HTTP call when starting the DXC

**Comment by woodyjon** [comment]
Yes ok.
The only thing is that it requires some change because that means we cannot connect to the smart contract before the user has entered his account id and api key.

**Comment by goosecoid** [comment]
> Yes ok.
> The only thing is that it requires some change because that means we cannot connect to the smart contract before the user has entered his account id and api key.

Indeed. It's maybe a lot of trouble but you never know that the id might change

**Comment by woodyjon** [comment]
I pushed the getting of infura id from the dxs.
As we need the connection data of the user and the ip of the dxs, I get the infura id when the user sets its account id and api key.

**Pull request merged**
