### PR TITLE
feat: unit testing database package

### PR DESCRIPTION
**Pull request by woodyjon**

### CODE REVIEW

**Comment by goosecoid** [comment]
How do you run those tests you wrote (database_test.go)?

You make a test suite by binding methods to the Suite struct and also some methods are known types by Suite (like after test). But how does TestInit work?

**Comment by woodyjon** [comment]
Suite is a package that allows setting up of stuff in the tests.
SetupSuite is automatically called.
You don't have to do anything special to launch the test. Usual commands work. The run-test.sh also works.

**Comment by woodyjon** [comment]
I think the TestInit is the only one which is called by go test, because it follows the testing standard, then it calls all the other suite stuff and test functions.

**Comment by goosecoid** [comment]
Yeah I commented out the call and it broke running the test, so I suppose you're correct. Anyways the test runs! So LGTM

**Comment by woodyjon** [comment]
That's how we can have one single setup for all test functions. It's because there is only one real test function.

**Pull request merged**
